# -*- coding: utf-8 -*-
"""Day02_Linear_regression_Fails_On_Nonlinear_and_polynomial _regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uv7xy4iKhBXS8L6w5tt2XEeJZUDArV-c

**Linear Model failing on Non Linear Data**
"""

#NON LINEAR DATA GENERATION
import torch
import torch.optim as optim
import torch.nn as nn
import matplotlib.pyplot as plt

torch.manual_seed(42)

X= torch.linspace(-10 , 10 , 200).reshape(-1, 1)
true_y = 3* X**2 + 2 + X
noise = torch.randn_like(X)*2
y = true_y + noise

# linear model
model= nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

# Training loop
losses = []
for epoch in range (200):
  y_pred = model(X)
  loss = criterion (y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  losses.append(loss.item())
  if epoch % 20 == 0:
    print (f"Epoch:{epoch},Loss:{loss.item():.4f}")

# plotting of results
with torch.no_grad():
  predictions= model(X)

  plt.scatter(X.numpy(),y.numpy(),label = "Noisy Data", alpha =0.4)
  plt.plot(X.numpy(),true_y.numpy(),label ="true curve", linewidth=3)
  plt.plot(X.numpy(), predictions.numpy(), label= " our linear model ", linewidth = 3)
  plt.legend()
  plt.show()

"""                                             **Polynomial Regression**"""

#data generation and non linear feature generation
import torch
import torch.optim as optim
import torch.nn as nn
import matplotlib.pyplot as plt

X= torch.linspace(-10, 10 , 200).reshape(-1,1)
true_y = 3* X**2 + 2*X +5
noise = torch.randn_like(X)*2
y = true_y+noise

# polynomial feature
X_poly = torch.cat([X,X**2], dim =1)         # we will get now (200,2) and dim = 1 is horizontal stacking as we have to add column not a row.
#normalization of featurees (
X_norm= (X_poly - X_poly.mean(dim =0))/X_poly.std(dim=0)# we have to normalize the features as the range was large for x**2 so its better to normalize it.
#Gradients scale is proportional to input magnitude. earlier (X range ~ 10) and (x**2 range~100) So: w₂ updates were ~10× larger thats why weights exploded.
# results in loss → inf → nan but after normalization (X_norm range ~1) and (X²_norm range ~1) Now both features contribute equally. Training becomes stable.

#normalisation of target also
y_norm = (y-y.mean())/y.std()

# linear model
poly_model = nn.Linear(2, 1)                     # our model linear only but as our features are non linear
                                            #so y = w1*feature1 + w2*feature2 + b but as feature 2 is X**2 it becomes polynomial regression.
criterion = nn.MSELoss()
optimizer = optim.SGD(poly_model.parameters(),lr =0.0001)   # also we have to reduce the learning rate from 0.01 to 0.0001
# why ?? because Polynomial features increase curvature. and High curvature → gradient changes rapidly → large steps are  unstable
#So even with normalization, high LR can cause: Oscillation ,Divergence , NaN
#Small learning rate: slow but stable descent

# TRAINING LOOP
losses=[]
for epoch in range(2000) :        # we increase epochs from 200 to 2000 as loss was decreasing very slowly which means its need time to reduce the loss
  y_pred = poly_model(X_norm)
  loss = criterion(y_pred, y_norm)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  losses.append(loss.item())
  if epoch % 200 ==0:
    print(f"epoch:{epoch}, poly_loss :{loss.item():.4f}")

"""Firstly i assumed the mse is small and loss is very less
But:

MSE ≈ 1.67
That is NOT small relative to normalized y scale.

If y ranges roughly from -1.2 to 2.4
Then squared error of 1.6 is large.

So the graph looking imperfect is mathematically consistent.

Nothing is broken.
"""

# plotting of results
with torch.no_grad():
  predictions= poly_model(X_norm)
  #true_y normalization
  true_y_norm = (true_y-true_y.mean())/true_y.std()

  plt.scatter(X_norm[:,0].numpy(),y_norm.squeeze().numpy(),label = "Noisy Data", alpha =0.4)# WE USE X_norm[:,0].numpy() BECAUSE X_norm is of size(200,2)
  plt.plot(X_norm[:,0].numpy(),true_y_norm.squeeze().numpy(),label ="true curve", linewidth=3)             # X_norm[:,0].numpy() makes it (200,)
  plt.plot(X_norm[:,0].numpy(),predictions.squeeze().numpy(), label= " our linear model ", linewidth = 3) # also y_norm is of size (200,1) so we have to mae it (200,)
  plt.legend()                                                                              #for that we use squeeze
  plt.show()