# -*- coding: utf-8 -*-
"""Decision_Boundary_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-tJKFTVXFQ4ffhY6G4dpxLfyFYwbsra
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# dataset generation and classification condition
torch.manual_seed(20)
N = 200
X = torch.randn(N,2)

y = (X[:,0]**2 + X[:,1]**2>1).long()

# dataset visualization
plt.figure(figsize=(6,6))
plt.scatter(X[:,0],X[:,1],c = y, cmap = "coolwarm")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Data Visualization")
plt.show()

model = nn.Sequential(
    nn.Linear(2, 32),
    nn.ReLU(),
    nn.Linear(32,32),
    nn.ReLU(),
    nn.Linear(32, 2)
)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr = 0.01)

#training loop
losses =[]
for epochs in range (200):
  logit= model(X)
  loss= criterion(logit, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  losses.append(loss.item())

  if epochs % 20 ==0:
    print(f"Epoch:{epochs}, training_loss :{loss.item():.4f}")

# prediction grid creation
X_min , X_max = X[:,0].min()-1, X[:,1].max()+1
y_min , y_max = X[:,1].min()-1, X[:,1].max()+1


xx , yy = torch.meshgrid (
    torch.linspace(X_min,X_max,200),  # Creates 200 evenly spaced numbers between X_min and X_max.
    torch.linspace(y_min,y_max,200),  # Creates 200 evenly spaced numbers between y_min and y_max.
    indexing ="ij"
)

grid = torch.cat([xx.reshape(-1,1),yy.reshape(-1,1)], dim = 1) #This prepares the grid for the neural network.

"""# Decision Boundary Visualization — Creating the Prediction Grid

To visualize the **decision boundary**, we must evaluate the neural network on many points across the entire 2D space.

The dataset only contains **200 points**, but to understand how the model classifies any location in the plane, we create a **dense grid of coordinates**.

This grid will later be passed through the neural network so that we can color each region according to the predicted class.

---

# Step 1 — Define the Range of the Grid

We first determine the range of the dataset.

```python
x_min, x_max = X[:,0].min() - 1, X[:,0].max() + 1
y_min, y_max = X[:,1].min() - 1, X[:,1].max() + 1
```

Explanation:

* `X[:,0]` → all x-coordinates (feature 1)
* `X[:,1]` → all y-coordinates (feature 2)

We subtract and add **1** to extend the region slightly beyond the dataset so the decision boundary is fully visible.

---

# Step 2 — Generate Evenly Spaced Coordinates

We create evenly spaced values between the minimum and maximum range.

```python
torch.linspace(x_min, x_max, 200)
torch.linspace(y_min, y_max, 200)
```

This generates **200 evenly spaced points** along each axis.

Example:

```
x values = [-2, -1, 0, 1, 2]
y values = [-2, -1, 0, 1, 2]
```

---

# Step 3 — Create a Grid of Coordinates

To evaluate every location in the plane, we need **all combinations of x and y**.

Example grid of coordinates:

```
(-2,-2) (-1,-2) (0,-2) (1,-2) (2,-2)
(-2,-1) (-1,-1) (0,-1) (1,-1) (2,-1)
(-2, 0) (-1, 0) (0, 0) (1, 0) (2, 0)
(-2, 1) (-1, 1) (0, 1) (1, 1) (2, 1)
(-2, 2) (-1, 2) (0, 2) (1, 2) (2, 2)
```

We generate this grid using:

```python
xx, yy = torch.meshgrid(...)
```

---

# Step 4 — Understanding `xx`

The matrix `xx` stores the **x-coordinate** of each grid point.

Example:

```
xx =
[[-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]]
```

Each row repeats the x-values because each row represents a different **y level**.

For example:

```
Row 1 → y = -2
Row 2 → y = -1
Row 3 → y = 0
```

The x-coordinates remain the same across rows.

---

# Step 5 — Understanding `yy`

The matrix `yy` stores the **y-coordinate** of each grid point.

Example:

```
yy =
[[-2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]
 [ 2  2  2  2  2]]
```

Each column repeats the y-value because each column corresponds to a different **x position**.

---

# Step 6 — Forming Coordinate Pairs

Each grid point is obtained by combining the matrices:

$$
(x, y) = (xx[i,j],; yy[i,j])
$$

Example:

```
xx[2,3] = 1
yy[2,3] = 0
```

So the coordinate becomes:

```
(1, 0)
```

---

# Step 7 — Total Grid Points

Because we created:

```
200 x-values
200 y-values
```

The total number of grid points becomes:

$$
200 \times 200 = 40000
$$

So we now have **40,000 coordinates covering the 2D plane**.

---

# Step 8 — Flatten the Grid

Neural networks expect input in the format:

```
(number_of_samples, number_of_features)
```

Example dataset shape:

```
(200, 2)
```

However, our grid matrices have shape:

```
(200, 200)
```

So we reshape them:

```python
xx.reshape(-1,1)
yy.reshape(-1,1)
```

This converts them into:

```
(40000, 1)
```

---

# Step 9 — Combine X and Y Coordinates

Finally, we combine the flattened coordinates:

```python
grid = torch.cat([xx.reshape(-1,1), yy.reshape(-1,1)], dim=1)
```

Resulting shape:

```
grid.shape = (40000, 2)
```

Example rows:

```
[-2 , -2]
[-1 , -2]
[ 0 , -2]
[ 1 , -2]
[ 2 , -2]
...
```

This format matches the dataset input structure.

---

# Key Idea

The grid represents **40,000 points covering the entire plane**.

We will feed these points into the neural network to ask:

> "What class would the model predict at each location?"

By coloring the predictions across the grid, we obtain the **decision boundary visualization**.

"""

# predict class for grid
with torch.no_grad():
  logits = model(grid) # THIS TIME WE ARE FINDING THE PREDICTION OF CLASS BY TRAINED MODEL ON GRID
  pred = torch.argmax(logits , dim = 1)  # logits.shape = (40000,2)  2 represent class 0 score and class 1 score for 40000 cordinate points
# and pred.shape =(40000)

  z = pred.reshape(xx.shape)      #reshape predictions back into a grid format.
                                  # Now every grid location has a predicted class.

# plotting of results
plt.figure(figsize=(6,6))
plt.contourf(xx.numpy(), yy.numpy(), z.numpy(),  cmap = "coolwarm", alpha = 0.3) #We use contourf instead of scatter because contourf colors the entire prediction space,
                                                                                 #Allowing us to visualize the decision boundary of the neural network.
plt.scatter(X[:,0],X[:,1], c=y ,cmap = "coolwarm") # this will plot the real data points
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

plt.show()

"""**Blue region = class 0**

**Red region = class 1**

# Difference Between `scatter` and `contourf`

Both `scatter` and `contourf` are visualization tools in **Matplotlib**, but they serve different purposes.

---

# 1. Scatter Plot

A scatter plot is used to visualize **individual data points**.

Example:

```python
plt.scatter(X[:,0], X[:,1], c=y, cmap="coolwarm")
```

What it shows:

* Each point represents a **single sample in the dataset**
* The color represents the **class label**

Example visualization:

```
● ● ● ●
● ● ● ●
```

Here:

* The x-axis represents **feature 1**
* The y-axis represents **feature 2**
* Each dot corresponds to a **data sample**

Scatter plots are useful for:

* Visualizing datasets
* Observing class distributions
* Detecting clusters or patterns

However, scatter plots **only show existing data points** and do not reveal how the model classifies the entire space.

---

# 2. Contourf Plot

`contourf` creates a **filled contour plot**, which colors entire regions of the plane.

Example:

```python
plt.contourf(xx, yy, Z, cmap="coolwarm", alpha=0.3)
```

What it shows:

* The **model's prediction for every point in the space**
* Colored regions representing predicted classes

Example visualization:

```
🔴🔴🔴🔴🔴
🔴🔵🔵🔵🔴
🔴🔵🔵🔵🔴
🔴🔴🔴🔴🔴
```

Here:

* Each region represents the **class predicted by the neural network**
* The border between colors represents the **decision boundary**

---

# 3. Why We Use Both Together

In decision boundary visualization we combine both:

```python
plt.contourf(xx, yy, Z, cmap="coolwarm", alpha=0.3)
plt.scatter(X[:,0], X[:,1], c=y, cmap="coolwarm")
```

Result:

* **Colored regions** → model predictions across the entire space
* **Dots** → actual dataset samples

This helps us visually verify whether the model learned the correct classification boundary.

---

# 4. Summary

| Plot Type     | Purpose                              |
| ------------- | ------------------------------------ |
| Scatter Plot  | Shows individual dataset samples     |
| Contourf Plot | Shows predicted regions of the model |

Scatter visualizes **data points**, while contourf visualizes **the model's decision space**.
"""

