# -*- coding: utf-8 -*-
"""gradient_clipping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDHOohVjJOqIKtr3vtbWr08b5rCcm_1g

# Gradient Clipping

## Objective

In this notebook we will understand why gradients sometimes explode during
training, how this breaks the optimization process, and how gradient clipping
fixes it with a single line of code.

---

## What Are Exploding Gradients?

During backpropagation, gradients are computed by multiplying values across
layers using the chain rule:

$$
\frac{\partial L}{\partial w_1} = \frac{\partial L}{\partial z_n} \cdot
\frac{\partial z_n}{\partial z_{n-1}} \cdot \ldots \cdot
\frac{\partial z_2}{\partial z_1}
$$

If these values are greater than 1, repeated multiplication across many
layers causes gradients to grow exponentially.

$$
2 \times 2 \times 2 \times 2 \times 2 = 32 \quad \text{(5 layers)}
$$

$$
2^{20} = 1{,}048{,}576 \quad \text{(20 layers)}
$$

This is called the **exploding gradient problem**.

---

## What Happens When Gradients Explode

The weight update rule is:

$$
w = w - \eta \cdot \nabla L
$$

If $\nabla L$ is extremely large, the update becomes enormous:

$$
w = w - 0.01 \times 1{,}000{,}000 = w - 10{,}000
$$

The weights jump to completely wrong values. On the next step the gradients
explode again in a different direction. Training becomes completely unstable
and loss diverges to infinity or NaN.

---

## What is Gradient Clipping?

Gradient clipping prevents this by limiting the magnitude of gradients
before the weight update happens.

The most common method is **norm clipping**:

$$
\text{if } \|\nabla L\| > \text{threshold} \quad \Rightarrow \quad
\nabla L = \frac{\nabla L}{\|\nabla L\|} \times \text{threshold}
$$

If the gradient norm exceeds the threshold, we scale it down so its norm
equals exactly the threshold. If it is already below the threshold we
leave it unchanged.

---

## Simple Intuition

Think of gradient clipping like a speed limit on a road.

- Cars can travel at any speed below the limit freely
- If a car exceeds the limit it is slowed down to exactly the limit
- The direction of travel does not change, only the speed is reduced

In the same way:

- Small gradients pass through unchanged
- Large gradients are scaled down to the threshold
- The direction of the gradient does not change, only the magnitude

---

## PyTorch Implementation

Gradient clipping in PyTorch is a single line added after
`loss.backward()` and before `optimizer.step()`:
```python
loss.backward()
torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
optimizer.step()
```

`max_norm` is the threshold. Any gradient whose norm exceeds this value
gets scaled down.

---

## Experiment Plan

We will run three experiments on the same model and dataset:

1. Normal training — baseline with a reasonable learning rate
2. Large learning rate without clipping — gradients explode
3. Large learning rate with clipping — gradients stabilized

We will compare:
- Training loss curves
- Gradient norms across training

---

## Where Gradient Clipping Is Used

| Model | Why Clipping Is Needed |
|---|---|
| RNN / LSTM | Gradients multiply across many time steps |
| Transformer | Very deep architecture with large gradients |
| Deep CNN | Many layers cause gradient accumulation |
| Any model with large learning rate | Updates become too aggressive |

---

## Key Insight

Gradient clipping does not fix the root cause of exploding gradients.
It is a safety mechanism that keeps training stable while the optimizer
navigates difficult regions of the loss landscape.
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
torch.manual_seed(20)

N = 200
X = torch.randn(N,2)
y = (X[:,0]+X[:,1]>0).long()
print(f"X shape:{X.shape}")
print(f"y shape:{y.shape}")
print(f"Class Distribution : {y.sum().item()} ones , {(y==0).sum().item()} zeros")

def create_model():
  return nn.Sequential(
    nn.Linear(2,64),
    nn.ReLU(),
    nn.Linear(64,64),
    nn.ReLU(),
    nn.Linear(64,64),
    nn.ReLU(),
    nn.Linear(64,2)

  )

#  training function  with clipping parameter
def train_model(model , X, y,learning_rate, epochs = 100, clip_norm ="None"):
  criterion = nn.CrossEntropyLoss()
  optimizer = optim.SGD(model.parameters(),lr = learning_rate)

  training_loss = []
  gradient_norms =[]

  for epoch in range (epochs):
    model.train()
    optimizer.zero_grad()
    predictions = model(X)
    loss = criterion(predictions,y)
    loss.backward()
    if clip_norm is not None:
      torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm = clip_norm)
    optimizer.step()

    training_loss.append(loss.item())

    layer_grads=[]
    for name , param in model.named_parameters():
      if param.grad is not None:
        layer_grads.append(param.grad.norm().item())
      gradient_norms.append(layer_grads)

    if epoch % 20 == 0:
      print(f"epoch:{epoch},training_loss:{loss.item():.4f}")
  return training_loss, gradient_norms

# model" 1 (normal learning rate , no clipping)
print("Model 1 : normal learning rate , no clipping")

model_1 = create_model()
training_loss_1,gradient_norms_1 = train_model(
    model_1, X, y, learning_rate = 0.01, epochs = 100, clip_norm= None
)
print(f"Final_loss: {training_loss_1[-1]:.4f}")
print(f"Max Gradient Norm seen: {max([max(g) for g in gradient_norms_1])}")
print(f"Gradient stability :Stable" )

# model 2 (large learning rate , without clipping)
print("Model 2: large learning rate , without clipping ")

model_2 = create_model()
training_loss_2, gradient_norms_2 = train_model(
  model_2 , X , y , learning_rate = 0.5, epochs = 100, clip_norm= None
)
print(f"Final_Loss:{training_loss_2[-1]:.4f}")
print(f"max grdient norm seen:{max([max(g) for g in gradient_norms_2])}")
print(f"Gradient stability : Exploded")

# model 3 (large learning rate ,with clipping)
print("Model 3 : large learning rate , with clipping")

model_3 = create_model()
training_loss_3, gradient_norms_3 = train_model(
    model_3, X, y, learning_rate = 0.5 , clip_norm = 1.0
)
print(f"Final_loss:{training_loss_3[-1]:.4f}")
print(f"max gradient norm seen:{max([max(g) for g in gradient_norms_3])}")
print(f"Gradient stability :Clipped")

"""## Understanding `grads_1` and `max([max(g) for g in grads_1])`

### What is `grads_1`?

`grads_1` is a **list of lists** that stores gradient norms across all epochs.

```python
grads_1 = [
    [0.234, 0.567, 0.123],  # Epoch 0: gradients from 3 layers
    [0.198, 0.512, 0.089],  # Epoch 1: gradients from 3 layers
    [0.156, 0.478, 0.045],  # Epoch 2: gradients from 3 layers
    ...
]
```

Each inner list contains the gradient norm for each layer in that epoch.

### Breaking Down `max([max(g) for g in grads_1])`

Reading from inside out:

**`for g in grads_1`** — Loop through each inner list (each epoch's gradients). `g` = one epoch's gradient list, like `[0.234, 0.567, 0.123]`

**`max(g)`** — Find the largest gradient norm in that epoch. For epoch 0: `max([0.234, 0.567, 0.123])` = `0.567`

**`[max(g) for g in grads_1]`** — This creates a new list with the max gradient from each epoch. Result: `[0.567, 0.512, 0.478, ...]`

**`max([...])`** — Find the largest value in that list. Result: `0.567` (the maximum gradient norm across all epochs and all layers)
"""

#plotting loss curve
fig, axes = plt.subplots(1,2 , figsize=(14,5)) #axes = array of axes objects (the individual plot areas)
# 1)Plot loss
ax= axes[0] # first left plot
ax.plot(training_loss_1,label="model_1: lr = 0.01, no clip",linewidth = 2 , color = "green")
ax.plot(training_loss_2, label ="model_2: lr = 0.5, no clip", linewidth= 2 , color="red")
ax.plot(training_loss_3, label = "model_3: lr = 0.5 , clip = 1.0", linewidth=2, color ="blue")
ax.set_xlabel("Epochs")
ax.set_ylabel("Loss")
ax.set_title("Training loss: Effect of gradient clipping")
ax.legend()
ax.grid(True)
ax.set_yscale('log')# Log scale so we can see both stable and exploding curves

#2)Plot Max gradient Norm per epoch
max_grad_1 = [max(g)for g in gradient_norms_1]
max_grad_2 = [max(g)for g in gradient_norms_2]
max_grad_3 = [max(g)for g in gradient_norms_3]

ax= axes[1]
ax.plot(max_grad_1,label = "model_1: lr = 0.01, no clip", linewidth= 2,color = "green")
ax.plot(max_grad_2,label ="model_2: lr = 0.5 , no clip ", linewidth = 2,color="red")
ax.plot(max_grad_3,label= "model_3: lr = 0.5, clip = 1.0 ",linewidth = 2, color ="blue")
ax.set_xlabel("Epochs")
ax.set_ylabel("Max_grad_norm")
ax.set_title("Max gradient per norm: Effect of gradient clipping")
ax.legend()
ax.grid(True)
ax.set_yscale("log")

plt.tight_layout()
plt.show()

"""## Two Ways to Use Matplotlib

### Method 1: Object-Oriented (Using `ax`)

```python
fig, axes = plt.subplots(1, 2)
ax = axes[0]

ax.plot(losses_1)
ax.set_xlabel("Epoch")
ax.set_ylabel("Loss")
ax.set_title("My Plot")
```

You explicitly work with the `ax` object. Commands start with `ax.set_...` or `ax.plot()`. You have direct control over which subplot you're working with.

### Method 2: Pyplot (Using `plt`)

```python
plt.plot(losses_1)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("My Plot")
plt.show()
```

You work with `plt` (pyplot interface). Commands start with `plt.set_...` or `plt.plot()`. Simpler syntax, but less control when you have multiple plots.

### When to Use Each

**Use `plt` (pyplot) when:**
- You have only 1 plot to make
- You want quick, simple code
- You don't need fine-grained control

```python
plt.plot([1, 2, 3, 4])
plt.xlabel("X")
plt.ylabel("Y")
plt.show()
```

**Use `ax` (object-oriented) when:**
- You have multiple subplots (2+ plots)
- You need to control each plot separately
- You want professional, scalable code

```python
fig, axes = plt.subplots(1, 2)

# Left plot
axes[0].plot(data1)
axes[0].set_xlabel("X")
axes[0].set_ylabel("Y")

# Right plot
axes[1].plot(data2)
axes[1].set_xlabel("X")
axes[1].set_ylabel("Z")

plt.show()
```

### Real Comparison

**Single Plot (Use `plt`)**

```python
import matplotlib.pyplot as plt

# Simple - just use plt
plt.plot([1, 2, 3, 4])
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training")
plt.show()
```

**Two Plots (Use `ax`)**

```python
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2)

# LEFT plot
axes[0].plot([1, 2, 3, 4])
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Loss")
axes[0].set_title("Training Loss")

# RIGHT plot
axes[1].plot([4, 3, 2, 1])
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Accuracy")
axes[1].set_title("Training Accuracy")

plt.show()
```

Why `ax` is necessary here: Without it, how would matplotlib know whether `plt.set_xlabel()` applies to the left plot or right plot? The `ax` object makes it explicit.

### Behind the Scenes

When you use `plt`:

```python
plt.plot(data)
plt.xlabel("X")
```

Matplotlib is actually doing this behind the scenes:

```python
fig = plt.gcf()  # Get current figure
ax = plt.gca()   # Get current axes
ax.plot(data)
ax.set_xlabel("X")
```

So `plt` is just a shortcut that works with a default, invisible `ax` object. When you have multiple plots, you need to explicitly specify which `ax` you're working with.

### Naming Convention

- `plt.xlabel()` ← No underscore, pyplot interface
- `ax.set_xlabel()` ← Underscore `set_`, object-oriented interface

This is just PyTorch/matplotlib convention. Both do the same thing.

## Observations and Insights OF THIS NOTEBOOK EXPERIMENT

### Three Experiments Compared

**Model 1 (Green):** Normal learning rate (0.01), no clipping. Loss stayed nearly flat around 0.6-0.59 range. The learning rate is so small that weight updates barely move the loss. Training is stable but very slow — gradient norms stayed at 0.206 max. This model would need 1000+ epochs to fully converge. The gradient norms plot shows a completely flat line near the bottom, indicating calm, predictable, but inefficient training.

**Model 2 (Red):** Large learning rate (0.5), no clipping. Loss plummeted from 0.6923 to 0.0095 in just 20 epochs — 50 times faster than green. This looks impressive at first glance. BUT the gradient norm plot reveals the truth: gradients spiked to 1.114 immediately and oscillated wildly throughout training. The model converged despite the instability, but this is risky behavior. In a more complex dataset or different initialization, this chaotic gradient behavior would cause divergence to NaN.

**Model 3 (Blue):** Large learning rate (0.5), WITH clipping. Loss descended almost identically to red (0.6777 to 0.0096) — same speed, same final loss. But crucially, gradient norms stayed controlled below 0.723 (our max_norm=1.0 threshold). Clipping achieved the speed of red with the stability of green. The gradient norm plot shows oscillations but they are orderly and bounded, never exceeding the clipping threshold.

### The Key Insight: Gradient Norms Tell the Real Story

The loss curves (left plot) are misleading on their own. Model 2 looks great because it converges fastest, but the gradient norm plot (right plot) reveals that Model 2 is chaotic while Model 3 is stable.

- **Green:** Small loss changes + calm gradients = stable but slow
- **Red:** Large loss changes + wild gradients = fast but unstable  
- **Blue:** Large loss changes + controlled gradients = fast AND stable ✓

Clipping didn't slow down convergence (blue matches red in speed). Instead, it made the fast convergence **safe** without sacrificing performance.

### Why This Matters

The gradient norm plot is more important than the loss plot. It shows whether training is actually stable or just lucky. Model 2's gradients oscillate wildly (peaking at 1.114) because the aggressive learning rate causes overshooting. With clipping (Model 3), those same gradients are scaled down to stay below 1.0, creating orderly training.

### When Gradients Explode (Theory vs Practice)

In theory, exploding gradients shoot to 10^6 or higher in deep RNNs. In this experiment, Model 2 only reached 1.114. Why the difference? Because:

- This is a **small, shallow network** (only 4 fully connected layers)
- We're training on **simple binary classification** (linearly separable data)
- Exploding gradients are most dangerous in **RNNs, LSTMs, and Transformers** where gradients multiply across many time steps or layers

In this controlled experiment, we see **mild instability** (oscillating gradients) rather than catastrophic explosion. But the principle is identical: clipping keeps gradients bounded and training stable.

### Practical Takeaway

Gradient clipping is a simple one-line fix that lets you use larger learning rates safely:

```python
torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
```

The cost is minimal (just scaling down large gradients proportionally). The benefit is huge (stable training, faster convergence, ability to use aggressive learning rates). This is why clipping is standard in production models like Transformers, RNNs, and any architecture where gradient flow is unpredictable.

### Final Comparison Table

| Aspect | Model 1 (Green) | Model 2 (Red) | Model 3 (Blue) |
|--------|---|---|---|
| **Learning Rate** | 0.01 | 0.5 | 0.5 |
| **Clipping** | No | No | Yes (1.0) |
| **Final Loss** | 0.5993 | 0.0095 | 0.0096 |
| **Max Grad Norm** | 0.206 | 1.114 | 0.723 |
| **Convergence Speed** | Slow | Fast | Fast |
| **Training Stability** | ✓ Stable | ✗ Chaotic | ✓ Stable |
| **Gradient Behavior** | Flat line | Wild spikes | Controlled oscillations |

Model 3 wins: **fastest convergence with stable, controlled training**.
"""

