# -*- coding: utf-8 -*-
"""minibatch_and_dataloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eafPJRBD9VnL5D9TQTXxMQ-q5-faBiQ2
"""

# data generation
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split

torch.manual_seed(42)
X = torch.linspace(-10,10,200).reshape(-1,1)
noise= torch.randn_like(X) * 2
true_y = 3*X**2 +2*X+5
y = true_y + noise
X_norm= (X-X.mean(dim=0))/ X.std(dim=0)
y_norm= (y-y.mean(dim=0))/ y.std(dim=0)

from torch.utils.data import TensorDataset , DataLoader
#train test split
X_train,X_test,y_train,y_test= train_test_split(X_norm,y_norm, test_size=0.2,random_state=42)
#creation of dataset objects
train_dataset= TensorDataset(X_train, y_train)     # now in our datset we will see (x1, y1), (x2,y2)....  dataset[i] → returns (X_train[i], Y_train[i])
test_datset= TensorDataset(X_test,y_test)          # now we will get dataset[i] → returns (X_test[i], Y_test[i])
                                                   # it simply bind features and labels together.
# why we need this binding ??
# Because DataLoader expects a dataset object that:
# 1) has length
# 2)can return one sample at a time
#TensorDataset provides that structure.


# data loader creation
train_loader = DataLoader(train_dataset, batch_size= 8 ,shuffle =True ) # shuffle = true , otherwise 1)Batches may contain sequential values (like increasing X)
test_loader = DataLoader(test_datset, batch_size= 8, shuffle= False)      #                          2) Model may learn biased patterns
                                                                           #                         3)Gradient updates become structured
                                                                           #                         4)Training becomes unstable
 # shuffle = True  ensures:
 #1) Random mixing,2) Better gradient estimation 3)Better generalization
 # and why shuffle = False in case of testing ??
 # because we are not training , so order doesnot matter ,We are just evaluating .


 #What  DataLoader do ??
 # DataLoader does three main things: 1)Splits dataset into batches, 2) Shuffles data (if enabled) ,3)Feeds batches during training

 #batch_size=8??
 #Instead of passing all 160 samples at once: we pass 8 samples at a time.
 #So training loop becomes: Batch 1 → 8 samples
 #                           Update weights
 #                  Batch 2 → next 8 samples
 #                            Update weights
 #                             ...
 #If total training samples = 160:
 #160 / 8 = 20 batches per epoch.
 #Batch 1 → 8 samples → update weights
 # Batch 2 → 8 samples → update weights
 #...
 #Batch 20 → update weights
 #So instead of 1 update per epoch (full batch),now we get 20 updates per epoch.This is Mini-Batch Gradient Descent.
 #Mini-batch introduces:
 #1)Gradient noise
 #2)Faster convergence
 #3)Better generalization

"""TensorDataset → wraps tensors into dataset structure

DataLoader → feeds dataset in mini-batches

This converts:

Full Batch Gradient Descent

into

Mini-Batch Gradient Descent
"""

model = nn.Squential(
    nn.Linear(1,64),
    nn.ReLU(),
    nn.Linear(64,1)
)
criterion  = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr = 0.005)

training_loss= []
testing_loss=[]

for epochs in range(300);
# training phase
  model.train()
  running_training_loss = 0.0

  for batch_X, batch_Y in train_loader:
    predictions= model(batch_X)
    loss = criterion(predictions,batch_Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    running_training_loss+=loss.item()

