# -*- coding: utf-8 -*-
"""multiclass_classification_softmax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqJRDOOQxN3TJE2mZe3LS204M03-m91O

# Multiclass Classification with Softmax

So far, we worked with **binary classification**, where the model predicts one of two classes.

Example:

```
class ∈ {0,1}
```

In many real-world problems we must classify among **multiple classes**:

```
class ∈ {0,1,2,...,K-1}
```

For example:

| Problem               | Classes                  |
| --------------------- | ------------------------ |
| Digit recognition     | 0–9                      |
| Animal classification | cat, dog, bird           |
| Language detection    | English, Spanish, French |

---

# Model Output (Logits)

A neural network produces **raw scores** for each class.

These scores are called **logits**.

Example output for one sample:

```
[2.1 , 0.3 , -1.2]
```

This means:

* class 0 score = 2.1
* class 1 score = 0.3
* class 2 score = -1.2

The highest score corresponds to the predicted class.

---

# Softmax Function

To convert logits into probabilities, we use the **Softmax function**.

$$
\sigma(z_i) = \frac{e^{z_i}}{\sum_j e^{z_j}}
$$

Properties of Softmax:

* Converts logits into **probabilities**
* Probabilities **sum to 1**
* Higher logit → higher probability

Example:

```
logits = [2.1 , 0.3 , -1.2]
```

Softmax output:

```
[0.78 , 0.18 , 0.04]
```

---

# Cross Entropy Loss

To train the model we use **CrossEntropyLoss**.

The loss measures how far the predicted probabilities are from the true class.

$$
L = - \sum y_i \log(p_i)
$$

Where:

* $y_i$ = true label
* $p_i$ = predicted probability

Lower loss means **better predictions**.

---

# Important PyTorch Detail

In PyTorch we **do not apply Softmax manually** when using:

```
nn.CrossEntropyLoss()
```

Because this loss function internally applies:

```
LogSoftmax + NLLLoss
```

Therefore the model should output **raw logits**, not probabilities.

Example model output shape:

```
(batch_size , num_classes)
```

Example:

```
(200 , 3)
```

This means:

```
200 samples
3 class scores per sample
```
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# 3 class dataset generation
N = 100

X0 = torch.randn(N,2)+ torch.tensor([-2,-2]) # so your class 0 is in region around (-2,-2) to do that we add torch.tensor(-2,-2)
y0 = torch.zeros(N).long() # y0 =[0, 0 , 0, 0, 0.......N]

X1 = torch.randn(N,2) + torch.tensor([2,0]) # so your class 1 is in region (2,0)
y1 = torch.ones(N).long()

X2 = torch.randn(N,2) + torch.tensor([0,2]) # so your class2 region is around(0,2)
y2= torch.ones(N).long() * 2

# combine dataset
X = torch.cat([X0,X1,X2],dim = 0)
y = torch.cat([y0,y1,y2],dim = 0)

# dataset visualisation
plt.figure(figsize=(6,6))
plt.scatter(X[:,0],X[:,1], c= y , cmap ="viridis")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("MultiClass Dataset")
plt.show()

# model creation
model = nn.Sequential(
    nn.Linear(2,32),
    nn.ReLU(),
    nn.Linear(32,32),
    nn.ReLU(),
    nn.Linear(32,3)
)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

# trianing loop
losses = []
for epochs in range (200):
  logits = model(X)
  loss = criterion(logits,y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  losses.append(loss.item())

  if epochs % 20 == 0:
    print(f"Epoch:{epochs}, training_loss:{loss.item():.4f}")

# plotting trainging loss
plt.figure(figsize=(6,6))
plt.plot(losses)
plt.xlabel("Epochs")
plt.ylabel("loss")

plt.title("Training Loss")
plt.grid(True)
plt.show()

# generation of grid for decision boundary

X_min , X_max = X[:,0].min()-1, X[:,0].max()+1
y_min , y_max = X[:,1].min()-1, X[:,1].max()+1

xx , yy = torch.meshgrid(
    torch.linspace(X_min,X_max,200),
    torch.linspace(X_min, X_max,200),
    indexing = "ij"
    )
grid = torch.cat([xx.reshape(-1,1),yy.reshape(-1,1)], dim = 1)

model.eval()
with torch.no_grad():
  logits = model(grid)
  pred = torch.argmax(logits , dim = 1)

z = pred.reshape(xx.shape)

# prediction plotting
plt.figure(figsize=(6,6))
plt.contourf(xx.numpy(), yy.numpy() , z.numpy(), cmap = "coolwarm")
plt.scatter(X[:,0],X[:,1],c= y, cmap="viridis")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("MultiClass Decision Boundary")
plt.show()

"""# Observations — Multiclass Classification with Softmax

## 1. Dataset Structure

The dataset contains **three distinct clusters** in a 2D feature space.

Each cluster represents a different class:

| Class   | Approximate Center |
| ------- | ------------------ |
| Class 0 | (-2 , -2)          |
| Class 1 | (2 , 0)            |
| Class 2 | (0 , 2)            |

Each class contains **100 samples**, resulting in a total dataset size of:

```
X shape = (300 , 2)
y shape = (300)
```

The clusters are generated using Gaussian noise and then shifted to different regions of the plane.

This makes the dataset **visually separable** and ideal for demonstrating multiclass classification.

---

# 2. Training Behaviour

The training loss decreased steadily during optimization:

| Epoch | Training Loss |
| ----- | ------------- |
| 0     | 1.1814        |
| 20    | 0.2088        |
| 40    | 0.1627        |
| 60    | 0.1489        |
| 80    | 0.1381        |
| 100   | 0.1285        |
| 120   | 0.1214        |
| 140   | 0.1160        |
| 160   | 0.1135        |
| 180   | 0.1099        |

Observations:

* The loss decreases smoothly, indicating **stable gradient descent optimization**.
* The large drop in the first few epochs suggests the model quickly learns the **basic separation between clusters**.
* Later epochs show slower improvement as the model fine-tunes the decision boundaries.

The initial loss is close to **1.1**, which is expected for random predictions in a **3-class problem**:

$$
L = -\log\left(\frac{1}{3}\right)
$$

This corresponds to predicting equal probability for all classes.

---

# 3. Decision Boundary Interpretation

The decision boundary plot shows **three colored regions**, each corresponding to the class predicted by the model.

* The background colors represent **model predictions across the entire feature space**.
* The scatter points represent the **actual dataset samples**.

| Element                 | Meaning           |
| ----------------------- | ----------------- |
| Colored regions         | Model predictions |
| Scatter points          | Real data samples |
| Boundary between colors | Decision boundary |

Most points lie inside their corresponding prediction region, indicating the model learned a **correct classification rule**.

---

# 4. Shape of the Decision Boundaries

The boundaries between classes appear **smooth but piecewise linear**.

This occurs because the network architecture used was:

```
Linear → ReLU → Linear
```

ReLU networks represent nonlinear functions using **piecewise linear approximations**.
Therefore, instead of perfectly curved boundaries, the model constructs boundaries using **multiple linear segments**.

---

# 5. Softmax-Based Multiclass Prediction

The neural network outputs **logits** for each class:

```
[z0 , z1 , z2]
```

These logits are converted into probabilities using the Softmax function:

$$
\sigma(z_i) = \frac{e^{z_i}}{\sum_j e^{z_j}}
$$

The predicted class is obtained using:

```
argmax(logits)
```

This selects the class with the **highest predicted score**.

---

# 6. Model Performance

The model successfully separates the three clusters:

* Class 0 region covers the **bottom-left cluster**
* Class 1 region covers the **right cluster**
* Class 2 region covers the **top cluster**

The decision regions align well with the dataset structure.

---

# 7. Key Insight

This experiment demonstrates several fundamental deep learning ideas:

* Neural networks can perform **multiclass classification**.
* Softmax converts raw model outputs into **probability distributions**.
* Cross-entropy loss drives the model to assign **higher probability to the correct class**.
* Decision boundaries learned by neural networks are **geometric partitions of feature space**.

---

# 8. Conclusion

The neural network successfully learned to partition the 2D space into **three distinct decision regions**, each corresponding to one class.

This experiment provides strong intuition about how deep learning models perform **multiclass classification using Softmax and cross-entropy optimization**.

"""

