# -*- coding: utf-8 -*-
"""Neural_Network_L2_regularisation_and_Dropout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_0NOSj9SKX8t1Bqmzi7ahBlvVbr3MNP

**SIMPLE NEURAL NETWORK**
"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

torch.manual_seed(42)

X= torch.linspace(-10,10,200).reshape(-1,1)
true_y = 3*X**2 + 2*X + 3
noise = torch.randn_like(X)
y = true_y + noise
#normalization for features
X_norm=(X-X.mean(dim =0))/X.std(dim = 0)
# normalisation of target also
y_norm=(y-y.mean())/y.std()          #why normalise output?? Because Neural networks train better when: 1) INPUTS ≈ N(0,1) Outputs ≈ N(0,1)
                                     # OTHERWISE Gradients become large AND Optimization slows

#train_ test_split
X_train, X_test,y_train,y_test = train_test_split(X_norm,y_norm,test_size=0.2,random_state=42)

from torch.nn.modules.activation import ReLU
# neural network
model = nn.Sequential(
    nn.Linear(1,128),
    nn.ReLU(),                              # RELU BRINGS NON LINEARITY TO OUR MODEL
    nn.Dropout(0.3),
    nn.Linear(128,64),                         #Each ReLU neuron can introduce one piecewise linear boundary, allowing the model to approximate curved functions.
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(64,1)

)
criterion= nn.MSELoss()
optimizer = optim.Adam(model.parameters(),lr = 0.005,weight_decay=1e-3)

# Training loop
training_losses=[]
evaluation_losses=[]

for epoch in range(1000):
 # training
 model.train()
 train_pred = model(X_train)
 train_loss = criterion(train_pred, y_train)

 optimizer.zero_grad()
 train_loss.backward()
 optimizer.step()

 # evaluation
 model.eval()                                           #why we use both model.eval()and torch.no_grad(). Because model.eval() Changes Layer Behavior
 with torch.no_grad():                                  #tells model to switch to evaluation mode , this disable  dropout . what is dropout??
  eval_pred = model(X_test)                             # during training Random neurons are turned off this is dropout so model.eval() disable dropout and all neurons are active now
  eval_loss = criterion(eval_pred,y_test)               #troch.no_grad() tells pytorch not to build the computational graph. effects 1) No gradient tracking 2)Less memory usage
                                                        #3)Faster inference 4)Cannot call .backward() . It affects autograd system only.
                                                        # so both solve different problems

  training_losses.append(train_loss.item())
  evaluation_losses.append(eval_loss.item())

  if epoch % 50 == 0 :
   print (f"Epoch:{epoch},training_loss:{train_loss.item():.4f}, evaluation_loss:{eval_loss.item():.4f}")

#plotting of results
model.eval()
with torch.no_grad():
  test_predictions= model(X_test)
  #sorting of test values for smooth plotting                # we did sorting as train_test_split do random shuffling and curve ploting will not be smooth
  sorted_indices = torch.argsort(X_test.squeeze())           # firstly we did X_test.squeeze what it do X_test SHAPE:(40,1) .squeeze do its shape to (40,) 1 dimension so that argsort can work
                                                             # argsort donot sort it but it provvide index whixh we will use to sort
  X_test_sorted = X_test.squeeze()[sorted_indices]
  y_test_sorted = y_test.squeeze()[sorted_indices]
  test_predictions_sorted= test_predictions.squeeze()[sorted_indices]

  plt.figure(figsize=(8,6))
  plt.scatter(X_test_sorted.numpy(),y_test_sorted.numpy(),label="Test Data",alpha=0.4)
  plt.plot(X_test_sorted.numpy(),test_predictions_sorted.numpy(),label="Model Predictions",linewidth=3)
  plt.legend()
  plt.title("Generalization Of Test Data")
  plt.show()

"""**SO IN LAST file **we did normal train test split and used normal neural network and the evaluation loss was the lowest as our dataset is not complex thats why l2 regularisation and dropout worsening the evaluation loss a little bit .

we need mostly regularisation when model capacity> data complexity
but in this case model capacity is sufficient for data complexity so no need of regularisation and dropout.

Dropout is more useful in:

Image classification

NLP

Very deep networks

But for regression with small data:

It introduces noise during training.

Although the network had high capacity, the underlying function was simple and the dataset sufficiently large relative to noise, so the model did not exhibit high variance. Therefore, additional regularization was unnecessary.

Regularisation increase bias and decrease variance but for our model it was already optimal so no need of regularisation

and regularisation is mostly used when variance is greater than bias

In this experiment, a simple regression problem was modeled using a neural network with sufficient capacity.

The base model (Linear → ReLU → Linear) achieved very low training and evaluation losses, indicating strong generalization.

When Dropout and L2 regularization were introduced, evaluation loss slightly increased. This suggests that the model was not suffering from high variance or overfitting in the first place.

Regularization techniques reduce variance by constraining model capacity, but they increase bias. In this case, the bias increase slightly outweighed any variance reduction, resulting in marginally worse performance.

This demonstrates that regularization is beneficial primarily when model variance is high (i.e., when overfitting occurs). For simple low-noise regression tasks with adequate data, additional regularization may not improve performance.
"""

