# -*- coding: utf-8 -*-
"""nn_lr_scheduler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKiWBBowre850hVdKWBJ-XULG8Gq6yp5
"""

# data generation
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split

torch.manual_seed(42)
X = torch.linspace(-10,10,200).reshape(-1,1)
noise= torch.randn_like(X) * 2
true_y = 3*X**2 +2*X+5
y = true_y + noise
X_norm= (X-X.mean(dim=0))/ X.std(dim=0)
y_norm= (y-y.mean(dim=0))/ y.std(dim=0)

from torch.utils.data import TensorDataset , DataLoader
#train test split
X_train,X_test,y_train,y_test= train_test_split(X_norm,y_norm, test_size=0.2,random_state=42)
#creation of dataset objects
train_dataset= TensorDataset(X_train, y_train)
test_datset= TensorDataset(X_test,y_test)


# data loader creation
train_loader = DataLoader(train_dataset, batch_size= 8 ,shuffle =True )
test_loader = DataLoader(test_datset, batch_size= 8, shuffle= False)

# model
model = nn.Sequential(
    nn.Linear(1,64),
    nn.ReLU(),
    nn.Linear(64,1)
)
criterion  = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr = 0.005)

#learning rate scheduler
scheduler = torch.optim.lr_scheduler.StepLR( optimizer, step_size = 50 , gamma = 0.5  ) # we created a object scheduler which controls how the learning rate changes during training.
# we are reducing learning rate gradualy because : 1)Early training → large steps help explore faster 2)Later training → smaller steps help fine-tune weights.
# scheduler needs the optimizer because lr belongs to optimizer , The scheduler simply modifies the optimizer's learning rate internally.
# step_size = 50 means Every 50 epochs → reduce the learning rate.
# gamma = 0.5 Gamma is the multiplication factor. new_lr = old_lr × gamma

# training loop

# we will apply early stopping
best_eval_loss = float("inf")
patience = 50
counter = 0
best_model_state = 0


training_losses= []
evaluation_losses=[]

for epochs in range(300):
# training phase
  model.train()
  running_training_loss = 0.0

  for batch_X, batch_Y in train_loader:
    predictions= model(batch_X)
    loss = criterion(predictions,batch_Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    running_training_loss+=loss.item()
  avg_training_loss = running_training_loss/len(train_loader)

  training_losses.append(avg_training_loss)

  #evaluation phase
  model.eval()
  with torch.no_grad():
    running_test_loss=0.0
    for batch_X,batch_Y in test_loader:
      predictions = model(batch_X)
      loss = criterion(predictions,batch_Y)
      running_test_loss+= loss.item()

    avg_test_loss = running_test_loss/len(test_loader)
    evaluation_losses.append(avg_test_loss)

    # Step the lr scheduler
    scheduler.step() # It tells the scheduler:Training finished for one epoch , Then scheduler checks: Has step_size epochs passed? If yes: Reduce learning rate
    current_lr = optimizer.param_groups[0]['lr']# Why we need this?? Because we want to print the learning rate.
   # What is param_groups?? Optimizers store parameters in groups.
   #optimizer
   # ├── param_groups
   #       ├── group 0
   #       │    ├── parameters
   #       │    └── learning_rate
   # So we access:
   # group 0 → learning rate
   # why [0]?
   # Because param_groups is a list.
   #So to access the first group we write: optimizer.param_groups[0]

    # early stopping logic
    if avg_test_loss < best_eval_loss:
      best_eval_loss = avg_test_loss
      counter = 0
      best_model_state = model.state_dict()
    else:
      counter +=1

    if counter >= patience :
      print(f"early stopping triggered at epoch: {epochs}")
      break

    # printing of losses
    if epochs % 50 == 0:
      print(f"Epoch:{epochs}, LR:{current_lr:.6f}, Training_loss:{avg_training_loss:.6f}, Evaluation_loss:{avg_test_loss:.6f}")
# restore best model
if best_model_state is not None:
    model.load_state_dict(best_model_state)
    print("best model weights restored")

"""# Why do optimizers allow multiple parameter groups?

Because sometimes different parts of the model need different learning rates.

### **Example Scenario**
Suppose you have:
* **Pretrained backbone**
* **New classifier layer**

You may want:
* **Backbone** $\rightarrow$ `lr = 0.0001`
* **Classifier** $\rightarrow$ `lr = 0.01`



So you define two parameter groups:

```python
optimizer = torch.optim.Adam([
    {'params': backbone.parameters(), 'lr': 0.0001},
    {'params': classifier.parameters(), 'lr': 0.01}
])

NOW:

param_groups[0] → backbone
param_groups[1] → classifier

But in our code we wrote:
optimizer = optim.Adam(model.parameters(), lr=0.005)

Here all parameters are in one group.

So internally:
param_groups = [ group0 ]

Just one element in the list.

Therefore:

optimizer.param_groups[0]['lr']

works.
"""

# PLOTTING
# 1) Train Loss vs Evaluation Loss
plt.figure(figsize=(8,6))
plt.plot(training_losses, label ="training_loss")
plt.plot(evaluation_losses , label ="evaluation_loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.grid(True)
plt.legend()
plt.show()

# 2) Model Predictions on X_test
model.eval()
with torch.no_grad():
  predictions =  model(X_test)
  sorted_indices= torch.argsort(X_test.squeeze())
  X_test_sorted = X_test.squeeze()[sorted_indices]
  predictions_sorted =predictions.squeeze()[sorted_indices]
  y_test_sorted= y_test.squeeze()[sorted_indices]
  plt.figure(figsize=(8,6))
  plt.scatter( X_test_sorted.numpy(),y_test_sorted.numpy(), label="Noisy test data", alpha=0.5)
  plt.plot(X_test_sorted.numpy(), predictions_sorted.numpy(), label="model predictions on test data", linewidth=3)
  plt.xlabel("X (Normalised)")
  plt.ylabel("y (Normalised)")
  plt.title("model predictions")
  plt.legend()
  plt.grid(True)
  plt.show()

"""**Learning Rate Scheduler
controls optimization**

**Early Stopping
controls generalization**
"""

