# -*- coding: utf-8 -*-
"""nn_minibatch_early_stopping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12SpGnmfD8mALWqwrx2QORV5L-T2MFuzZ
"""

# data generation
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.model_selection  import train_test_split

torch.manual_seed(42)
X = torch.linspace(-10,10,200).reshape(-1,1)
noise= torch.randn_like(X) * 2
true_y = 3*X**2 +2*X+5
y = true_y + noise
X_norm= (X-X.mean(dim=0))/ X.std(dim=0)
y_norm= (y-y.mean(dim=0))/ y.std(dim=0)

from torch.utils.data import TensorDataset , DataLoader
#train test split
X_train,X_test,y_train,y_test= train_test_split(X_norm,y_norm, test_size=0.2,random_state=42)
#creation of dataset objects
train_dataset= TensorDataset(X_train, y_train)     # now in our datset we will see (x1, y1), (x2,y2)....  dataset[i] → returns (X_train[i], Y_train[i])
test_datset= TensorDataset(X_test,y_test)          # now we will get dataset[i] → returns (X_test[i], Y_test[i])
                                                   # it simply bind features and labels together.
# why we need this binding ??
# Because DataLoader expects a dataset object that:
# 1) has length
# 2)can return one sample at a time
#TensorDataset provides that structure.


# data loader creation
train_loader = DataLoader(train_dataset, batch_size= 8 ,shuffle =True ) # shuffle = true , otherwise 1)Batches may contain sequential values (like increasing X)
test_loader = DataLoader(test_datset, batch_size= 8, shuffle= False)      #                          2) Model may learn biased patterns
                                                                           #                         3)Gradient updates become structured
                                                                           #                         4)Training becomes unstable
 # shuffle = True  ensures:
 #1) Random mixing,2) Better gradient estimation 3)Better generalization
 # and why shuffle = False in case of testing ??
 # because we are not training , so order doesnot matter ,We are just evaluating .


 #What  DataLoader do ??
 # DataLoader does three main things: 1)Splits dataset into batches, 2) Shuffles data (if enabled) ,3)Feeds batches during training

 #batch_size=8??
 #Instead of passing all 160 samples at once: we pass 8 samples at a time.
 #So training loop becomes: Batch 1 → 8 samples
 #                           Update weights
 #                  Batch 2 → next 8 samples
 #                            Update weights
 #                             ...
 #If total training samples = 160:
 #160 / 8 = 20 batches per epoch.
 #Batch 1 → 8 samples → update weights
 # Batch 2 → 8 samples → update weights
 #...
 #Batch 20 → update weights
 #So instead of 1 update per epoch (full batch),now we get 20 updates per epoch.This is Mini-Batch Gradient Descent.
 #Mini-batch introduces:
 #1)Gradient noise
 #2)Faster convergence
 #3)Better generalization

"""TensorDataset → wraps tensors into dataset structure

DataLoader → feeds dataset in mini-batches

This converts:

Full Batch Gradient Descent

into

Mini-Batch Gradient Descent
"""

# model
model = nn.Sequential(
    nn.Linear(1,64),
    nn.ReLU(),
    nn.Linear(64,1)
)
criterion  = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr = 0.005)

# training loop

# we will apply early stopping
best_eval_loss = float("inf")
patience = 50
counter = 0
best_model_state = 0


training_losses= []
evaluation_losses=[]

for epochs in range(300):
# training phase
  model.train()
  running_training_loss = 0.0

  for batch_X, batch_Y in train_loader:
    predictions= model(batch_X)
    loss = criterion(predictions,batch_Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    running_training_loss+=loss.item() # WE ARE ADDING LOSS OF EACH BATCH SO ITS BECOME TOTAL LOSS OVER ALL TRAIN BATCHES FOR THAT PARTICULAR EPOCH
  avg_training_loss = running_training_loss/len(train_loader)   # len(train_loader) gives no of batches in epoch
                                                              # why to average the loss ?? if we will dont average the loss then it will depend on batch_size
  training_losses.append(avg_training_loss)

  #evaluation phase
  model.eval()
  with torch.no_grad():
    running_test_loss=0.0
    for batch_X,batch_Y in test_loader:
      predictions = model(batch_X)
      loss = criterion(predictions,batch_Y)
      running_test_loss+= loss.item()

    avg_test_loss = running_test_loss/len(test_loader)
    evaluation_losses.append(avg_test_loss)
    # early stopping logic
    if avg_test_loss < best_eval_loss:   # we are applying early stopping logic because : 1) Prevents unnecessary training 2)Prevents deeper overfitting
      best_eval_loss = avg_test_loss     #                                                 3)Saves computation 4)Preserves best model behavior window.
      counter = 0
      best_model_state = model.state_dict()# if validation improved(means avg_test_loss < best_eval_loss) → save weights
    else:
      counter +=1

    if counter >= patience :
      print(f"early stopping triggered at epoch: {epochs}")
      break

    # printing of losses
    if epochs % 50 == 0:
      print(f"Epoch:{epochs}, Training_loss:{avg_training_loss}, Evaluation_loss:{avg_test_loss}")
# restore best model
if best_model_state is not None:
    model.load_state_dict(best_model_state)  # we are doing this step as we find best parametes at epoch =100 but our training will stop at epoch = 100 + patience
    print("best model weights restored")      # so to get the best parameters we load model to the best_model_parametes which we stored above .

"""**why to average the loss ??**

lets understand through an example :

**Case 1:**
160 training samples,
Batch size = 8
→ 20 batches

Total running loss = 8.2

**Case 2**

160 training samples,
Batch size = 16
→ 10 batches

Now running loss might be: 4.1

**Even if model performance is identical.**
**The total loss depends on how many batches we have.**
**That makes comparison meaningless.**

**BENIFIT OF DOING AVERAGE:**

avg_train_loss = running_train_loss / len(train_loader)

Now:

**Case1:** 8.2 / 20 = 0.41

**Case2:** 4.1 / 10 = 0.41

Same value. Now it reflects: Average loss per batch

Which reflects:

Model performance

Not dataset size or batch size.

**WHY WE USE BATCHES IN EVALUATION BUT WE WILL NOT USE THEM FOR PLOTTING ??
**

**We use batches because:**

1)We want to compute loss in mini-batches,
2)It keeps memory efficient,
3)It mirrors training structure,
4)It works for large datasets.

**But Plotting Is Different**

When plotting:

1)We are not training.
2)We are not updating weights.
3)We are not computing gradients.

We just want:

All predictions on test data.
"""

# PLOTTING
# 1) Train Loss vs Evaluation Loss
plt.figure(figsize=(8,6))
plt.plot(training_losses, label ="training_loss")
plt.plot(evaluation_losses , label ="evaluation_loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.grid(True)
plt.legend()
plt.show()

# 2) Model Predictions on X_test
model.eval()
with torch.no_grad():
  predictions =  model(X_test)
  sorted_indices= torch.argsort(X_test.squeeze())
  X_test_sorted = X_test.squeeze()[sorted_indices]
  predictions_sorted =predictions.squeeze()[sorted_indices]
  y_test_sorted= y_test.squeeze()[sorted_indices]
  plt.figure(figsize=(8,6))
  plt.scatter( X_test_sorted.numpy(),y_test_sorted.numpy(), label="Noisy test data", alpha=0.5)
  plt.plot(X_test_sorted.numpy(), predictions_sorted.numpy(), label="model predictions on test data", linewidth=3)
  plt.xlabel("X (Normalised)")
  plt.ylabel("y (Normalised)")
  plt.title("model predictions")
  plt.legend()
  plt.grid(True)
  plt.show()

"""Using **early stopping and restoring the best parameters to model** we can see that our graph is better than complete training ."""

