# -*- coding: utf-8 -*-
"""softmax_probability_heatmaps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hwqvk3MamR7EePEfnq6UII1REXwf3LGB

# Softmax Probability Heatmaps

In multiclass classification, the neural network outputs **logits** for each class:

$$
z = [z_0, z_1, z_2, ..., z_{K-1}]
$$

These logits are converted into probabilities using the **Softmax function**:

$$
\sigma(z_i) = \frac{e^{z_i}}{\sum_j e^{z_j}}
$$

This produces a probability distribution:

$$
p = [p_0, p_1, p_2, ..., p_{K-1}]
$$

where:

* $p_i \in [0,1]$
* $\sum_i p_i = 1$

---

# Why Heatmaps?

Previously, we visualized only:

```
argmax(logits)
```

which gives the **predicted class**.

However, this hides important information:

* How confident is the model?
* Where is the model uncertain?
* How do probabilities change across space?

---

# Softmax Heatmaps

Instead of plotting only predicted classes, we visualize:

$$
P(\text{class } i)
$$

across the entire feature space.

This produces **heatmaps** that show:

* High probability → strong confidence
* Low probability → weak confidence

---

# Key Insight

Decision boundaries occur where probabilities are equal:

$$
P(class;i) = P(class;j)
$$

Heatmaps allow us to see:

* smooth transitions between classes
* uncertainty regions
* confidence peaks

---

# Goal of This Experiment

We will:

1. Train a multiclass classifier
2. Compute softmax probabilities on a grid
3. Plot heatmaps for each class

This helps us understand **how neural networks assign confidence across space**.
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# 3 class dataset generation
N = 100

X0 = torch.randn(N,2)+ torch.tensor([-2,-2]) # so your class 0 is in region around (-2,-2) to do that we add torch.tensor(-2,-2)
y0 = torch.zeros(N).long() # y0 =[0, 0 , 0, 0, 0.......N]

X1 = torch.randn(N,2) + torch.tensor([2,0]) # so your class 1 is in region (2,0)
y1 = torch.ones(N).long()

X2 = torch.randn(N,2) + torch.tensor([0,2]) # so your class2 region is around(0,2)
y2= torch.ones(N).long() * 2

# combine dataset
X = torch.cat([X0,X1,X2],dim = 0)
y = torch.cat([y0,y1,y2],dim = 0)

# dataset visualisation
plt.figure(figsize=(6,6))
plt.scatter(X[:,0],X[:,1], c= y , cmap ="viridis")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("MultiClass Dataset")
plt.show()

# model creation
model = nn.Sequential(
    nn.Linear(2,32),
    nn.ReLU(),
    nn.Linear(32,32),
    nn.ReLU(),
    nn.Linear(32,3)
)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

# trianing loop
losses = []
for epochs in range (200):
  logits = model(X)
  loss = criterion(logits,y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  losses.append(loss.item())

  if epochs % 20 == 0:
    print(f"Epoch:{epochs}, training_loss:{loss.item():.4f}")

# plotting trainging loss
plt.figure(figsize=(6,6))
plt.plot(losses)
plt.xlabel("Epochs")
plt.ylabel("loss")

plt.title("Training Loss")
plt.grid(True)
plt.show()

# generation of grid for decision boundary

X_min , X_max = X[:,0].min()-1, X[:,0].max()+1
y_min , y_max = X[:,1].min()-1, X[:,1].max()+1

xx , yy = torch.meshgrid(
    torch.linspace(X_min,X_max,200),
    torch.linspace(y_min, y_max,200),
    indexing = "ij"
    )
grid = torch.cat([xx.reshape(-1,1),yy.reshape(-1,1)], dim = 1)

model.eval()
with torch.no_grad():
  logits = model(grid)
  pred = torch.softmax(logits , dim = 1) # it will give us [P(class0), P(class1), P(class2]

# Reshaping
p0 = pred[:,0].reshape(xx.shape) # probability map for class 0
p1 = pred[:,1].reshape(xx.shape) # probability map for class 1
p2 = pred[:,2].reshape(xx.shape) # probability map for class 2

"""# Why Softmax Instead of Argmax?

In classification, we can interpret model outputs in two ways:

---

## Argmax (Final Prediction)

```python
pred = torch.argmax(logits, dim=1)
```

* Returns the **class with the highest score**
* Gives a **hard decision**

Example:

```
logits = [2.5 , 1.2 , 0.3]
argmax → class 0
```

---

## Softmax (Probabilities)

$$
\sigma(z_i) = \frac{e^{z_i}}{\sum_j e^{z_j}}
$$

* Converts logits into **probabilities**
* Shows **confidence for each class**

Example:

```
logits = [2.5 , 1.2 , 0.3]
softmax → [0.70 , 0.20 , 0.10]
```

Meaning:

* 70% confident → class 0
* 20% → class 1
* 10% → class 2

---

## Key Difference

| Method  | Output                   | Information              |
| ------- | ------------------------ | ------------------------ |
| Argmax  | Class index              | Only prediction          |
| Softmax | Probability distribution | Confidence + uncertainty |

---

## Why We Use Softmax Here

In this notebook, we want to visualize:

* how confident the model is
* where the model is uncertain
* how probabilities change across space

Argmax only shows **which class**, while softmax shows **how strongly the model believes in each class**.

---

## One-Line Insight

$$
\text{argmax → decision} \quad \text{softmax → confidence}
$$

"""

# Heatmap plotting
fig , axes = plt.subplots(1,3, figsize = (18 ,5))  # fig is entire  figure (whole image)
# What is plt.subplots()??
# This function creates: a figure + multiple plots (subplots)
# plt.subplots(1,3) means : 1 row , 3 columns  [ plot1 | plot2 | plot3 ]
# what is axes ?? it  is a list (array) of individual plots.
# Since we created 3 plots:  axes[0] → first plot
#                            axes[1] → second plot
#                            axes[2] → third plot

# Class 0 :
axes[0].contourf(xx.numpy(),yy.numpy(), p0.numpy(), cmap ="viridis")
axes[0].set_title("P(class 0)")

# Class 1 :
axes[1].contourf(xx.numpy(),yy.numpy(),p1.numpy(),cmap ="viridis")
axes[1].set_title("P(class 1)")

#Class 3 :
axes[2].contourf(xx.numpy(),yy.numpy(),p2.numpy(),cmap ="viridis")
axes[2].set_title("P(class 2)")

plt.show()

# combining (1). Softmax heatmap (model confidence).and (2). Scatter plot (real data)
# main purpose of this cell is To compare model confidence with actual data points

fig , axes = plt.subplots(1, 3 , figsize = (18,5))

axes[0].contourf(xx.numpy(),yy.numpy(),p0.numpy(),cmap ="viridis")
axes[0].scatter(X[:,0],X[:,1], c= y , edgecolors ="white")
axes[0].set_title(("P(class 0)"))

axes[1].contourf(xx.numpy(),yy.numpy(),p1.numpy(),cmap ="viridis")
axes[1].scatter(X[:,0],X[:,1], c= y , edgecolors ="white")
axes[1].set_title(("P(class 1)"))

axes[2].contourf(xx.numpy(),yy.numpy(),p2.numpy(),cmap ="viridis")
axes[2].scatter(X[:,0],X[:,1], c= y , edgecolors ="white")
axes[2].set_title(("P(class 2)"))

plt.show()

"""# Observations — Softmax Probability Heatmaps

---

## Training Behavior

* Training loss decreases smoothly from **1.14 → 0.06**
* Indicates stable and effective learning
* Model successfully learns to separate the three classes

---

## Probability Heatmaps Interpretation

Each subplot represents:

$$
P(\text{class } i)
$$

across the 2D space.

* Bright regions → high confidence
* Dark regions → low confidence
* Intermediate colors → uncertainty

---

## Key Observations

### 1. Correct Region Learning

* Each class shows **high probability near its cluster center**
* Model correctly identifies spatial regions of each class

---

### 2. Smooth Transitions

* Boundaries between classes are **not sharp**
* Probabilities change gradually across regions

This reflects:

$$
P(class_i) + P(class_j) \approx 1 \quad \text{near boundaries}
$$

---

### 3. Uncertainty Regions

* Mixed-color areas (green/blue) indicate **model uncertainty**
* These occur near overlapping regions between classes

---

### 4. Confidence Peaks

* Centers of clusters show **very high confidence**
* Indicates strong learning of class-specific features

---

## Important Insight

Unlike decision boundaries (argmax), softmax heatmaps reveal:

* model confidence
* uncertainty zones
* smooth probability transitions

---

## Final Conclusion

The model:

* correctly learns class regions
* produces smooth decision boundaries
* expresses uncertainty in overlapping areas

This demonstrates a well-trained multiclass classifier with meaningful probability outputs.

"""

