# -*- coding: utf-8 -*-
"""softmax_crossentropy_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fY6i34plB2qe7BSAfMrnR5s7pzd8LP9u

# Softmax and CrossEntropy Loss for Classification

In classification tasks, neural networks must predict **which class an input belongs to**.

Unlike regression problems (which predict continuous values), classification models produce **scores for each class**.

These scores are called **logits**.

Example:

```
logits = [2.1, 0.5, 3.0]
```

Logits are **not probabilities**.
They can be any real numbers.

To convert logits into probabilities, we apply the **Softmax function**.

---

# Softmax Function

Softmax converts logits into probabilities that sum to 1.

$$
\sigma(z_i) = \frac{e^{z_i}}{\sum_{j=1}^{K} e^{z_j}}
$$

Where:

* $z_i$ is the logit for class $i$
* $K$ is the number of classes

Properties of Softmax:

* outputs values between **0 and 1**
* probabilities **sum to 1**
* the largest logit gets the **largest probability**

Example:

```
logits = [2.0, 1.0, 0.1]
```

Softmax probabilities:

```
[0.66, 0.24, 0.10]
```

---

# CrossEntropy Loss

CrossEntropy measures the difference between:

* predicted probabilities
* true class labels

The loss function is:

$$
L = - \sum_{i=1}^{C} y_i \log(p_i)
$$

Where:

* $y_i$ = true label (one-hot encoded)
* $p_i$ = predicted probability
* $C$ = number of classes

If the model assigns **low probability to the correct class**, the loss becomes large.

If the model assigns **high probability to the correct class**, the loss becomes small.

---

# Softmax + CrossEntropy in PyTorch

PyTorch provides a built-in function:

```
nn.CrossEntropyLoss()
```

Important:

* input → **raw logits**
* target → **class index**

Example:

```
logits = model(X)
loss = criterion(logits, y)
```

PyTorch automatically applies:

Softmax → Log → CrossEntropy

This implementation is **numerically stable and widely used in deep learning**.
"""

# import
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset , DataLoader
import matplotlib.pyplot as plt

# classification dataset generation
torch.manual_seed(20)

N= 200
X = torch.randn(N,2) # our data will be of shape [200,2] , example of X [
                                                                         #[ 0.23, -0.91],
                                                                         #[ 1.54,  0.12],
                                                                         #[-0.78,  0.55],
                                                                         #  ...
                                                                       #]

# classification rule
y = (X[:,0]**2 + X[:,1]**2 > 1).long()

# we use the classification criteria of circle and point outside of circle is true class which is class 1 and any point inside the class is class 0 .
# we used long() to convert class label into integer as we will further going to use cross entropy which need intergers class indices.

# visulaisation of dataset
plt.figure(figsize=(6,6))
plt.scatter(X[:,0],X[:,1], c=y , cmap ="coolwarm") # (xcoordinate, ycoordinate, c= y means color each point according to its class label, cmap selcts the color scheme for eg 0 → blue , 1 → red)
plt.xlabel("Feature1")
plt.ylabel("Feature2")
plt.title("Classification Dataset")
plt.show()

# neural network defination

model = nn.Sequential(
    nn.Linear(2,32),
    nn.ReLU(),
    nn.Linear(32,32),
    nn.ReLU(),
    nn.Linear(32,2)
)

#loss function and optimizer
criterion = nn. CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.01)

# training loop
losses =[]
for epochs in range(200):
  logits = model(X)
  loss = criterion(logits,y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  losses.append(loss.item())

  if epochs % 20 == 0:
    print(f"Epoch:{epochs}, loss:{loss.item():.4f} ")

# plotting for training loss
plt.figure(figsize=(8,6))
plt.plot(losses)
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Cross_Entropy_Training_Loss")
plt.grid(True)
plt.show()

with torch.no_grad():
  logits= model(X) # this model is trained model and we are  making prediction on X on  the trained model which we get from above process
  # logits are the raw scores for each class.
  predictions = torch.argmax(logits, dim = 1) # argmax finds the index of the largest value.
  #Why dim=1 ?
  # Because rows represent samples.
  #logits =
  #[
     # [2.3 , -1.2] for input 1     [class0_score , class1_score]
     # [-0.4 , 1.7] for input 2
     # [3.1 , -0.5] for input 3 and so on till input number 200.
  #]
  #We want the maximum across columns so dim = 1

  # dim = 1 no of classes as we hve 2 class so 2 classes
  # dim = no of samples as we have 200 sample so 200 smples

  #[2.3,-1.2] comes under dim = 1  and dim = 1 have 2 indexex index = 0 and index = 1 out which argmx will findout the index with higher value for every single input.
  # for eg for [2.3,-1.2]  Largest value = 2.3 so Index = 0 , So prediction: class0_score

# PLOTTING OF PREDICTIONS
plt.figure(figsize=(8,6))
plt.scatter(X[:,0],X[:,1], c = predictions, cmap ="coolwarm")
plt.xlabel("Feature1")
plt.ylabel("Feature2")
plt.title("predictions")
plt.grid(True)
plt.show()

"""# Observations

### 1. Dataset Structure

The dataset consists of two classes generated using a circular rule:

$$
x^2 + y^2 > 1
$$

Points inside the circle belong to **class 0**, while points outside the circle belong to **class 1**.

This creates a **non-linear classification problem**, meaning the classes cannot be separated by a straight line.

---

### 2. Training Loss Behavior

The CrossEntropy loss decreases smoothly during training:

| Epoch | Loss   |
| ----- | ------ |
| 0     | 0.667  |
| 20    | 0.121  |
| 40    | 0.032  |
| 60    | 0.017  |
| 100   | 0.0079 |
| 180   | 0.0026 |

This indicates that the model is **successfully learning the classification boundary**.

A decreasing CrossEntropy loss means the model is assigning **higher probabilities to the correct classes**.

---

### 3. Model Predictions

The prediction plot shows that the neural network correctly separates the two classes.

* Blue points correspond to **class 0 (inside the circle)**
* Red points correspond to **class 1 (outside the circle)**

The predicted labels closely match the true dataset structure.

---

### 4. Role of the Neural Network

A linear model would produce a straight decision boundary and would fail on this dataset.

However, the neural network contains multiple layers with **ReLU activations**, allowing it to learn **nonlinear decision boundaries**.

This enables the model to approximate the circular boundary defined by the dataset.

---

### 5. Key Insight

This experiment demonstrates that neural networks can learn **complex nonlinear patterns** from data using:

* hidden layers
* nonlinear activations
* gradient-based optimization

The model successfully learns a decision boundary that approximates the circular rule used to generate the dataset.

"""

